#Requires -Version 5.1
<#
.SYNOPSIS
  Path and plugin-manifest constants for the Codex adapter.

.DESCRIPTION
  Kept inside adapters/codex so parallel US waves do not mutate scripts/_lib.
#>

$script:CodexPathConstant = @{
    CoreDirectoryName              = 'core'
    SkillsDirectoryName            = 'skills'
    PolicyDirectoryName            = 'policy'
    PluginRootDirectoryName        = 'plugin'
    PluginManifestDirectoryName    = '.codex-plugin'
    PluginManifestFileName         = 'plugin.json'
    SkillManifestFileName          = 'SKILL.md'
    SharedSkillsDirectoryName      = '_shared'
    SddDirectoryName               = 'sdd'
    RulesDirectoryName             = 'rules'
    GuardrailsFileName             = 'guardrails.md'
    OfficialCodexHomeRelativePath  = '.codex'
    AgentsDirectoryName            = '.agents'
    PluginsDirectoryName           = 'plugins'
    MarketplaceFileName            = 'marketplace.json'
    PlaceholderToolkitRoot         = '{{TOOLKIT_ROOT}}'
    PlaceholderSddRoot             = '{{SDD_ROOT}}'
    PlaceholderGuardrailsPath      = '{{GUARDRAILS_PATH}}'
    TextFileExtensionPattern       = '\.(md|mdc|json|ps1|yml|yaml|txt)$'
    PathSeparatorForwardSlash      = '/'
    PluginSkillsManifestRelative   = './skills/'
    PluginMarketplaceSourcePath    = './plugin'
    PluginMarketplaceSourceKind    = 'local'
    PluginName                     = 'agent-dev-toolkit'
    PluginVersion                  = '0.1.0'
    PluginDescription              = 'Agent Dev Toolkit skills packaged as a Codex plugin for fixture and CI smoke.'
    PluginDisplayName              = 'Agent Dev Toolkit'
    MarketplaceName                = 'agent-dev-toolkit-local'
    MarketplaceDisplayName         = 'Agent Dev Toolkit (fixture)'
    MarketplacePluginCategory      = 'Productivity'
    MarketplacePolicyInstallation  = 'AVAILABLE'
    MarketplacePolicyAuthentication = 'ON_INSTALL'
    RouterDirectoryName            = 'router'
    AgentsFileName                 = 'AGENTS.md'
    SkillsCatalogDirectoryName     = 'skills-catalog'
    SkillsCatalogFileName          = 'CATALOG.md'
    HelpSkillsSkillId              = 'help-skills'
    PlaceholderResidualPattern     = '\{\{[^}]+\}\}'
    RepoDocsBacktickLinkPattern    = '`docs/[A-Za-z0-9._/-]+`'
    RepoDocsBarePathPattern        = '(?m)(?<![\w./-])docs/[A-Za-z0-9._/-]+'
    CursorRuleExtension            = '.mdc'
    MarkdownExtension              = '.md'
    RouterDualRootHeading          = '## Codex dual-root paths (installed)'
    RouterHomeSkillsTableLabel     = 'Home skills (`$` discovery / InstallRoot/skills)'
    HooksDirectoryName             = 'hooks'
    HooksFileName                  = 'hooks.json'
    HooksSessionStartScriptName    = 'session_start.ps1'
    HooksDefaultRelativePath       = './hooks/hooks.json'
    HooksSessionStartEventName     = 'SessionStart'
    HooksCommandType               = 'command'
    HooksSessionStartStatusMessage = 'Loading Agent Dev Toolkit Codex plugin context'
    HooksSessionStartCommandTemplate = 'pwsh -NoProfile -File "${PLUGIN_ROOT}/hooks/session_start.ps1"'
    HooksDescription               = 'Minimal Codex plugin lifecycle hooks for agent-dev-toolkit (files only; trust via /hooks is manual).'
    HooksTrustComment              = 'RN03: smoke asserts hooks files only - never invoke or require Codex /hooks trust UI.'
    UserScopeParameterName         = 'UserScope'
    UserSkillsRelativePath         = '.agents/skills'
    HomeSkillsRelativePath         = 'skills'
    UserScopeDescription           = 'Optional -UserScope also mirrors core/skills to USER discovery (InstallRoot/.agents/skills or live $HOME/.agents/skills). Opt-in only — enabling it together with always-on InstallRoot/skills (~/.codex/skills) duplicates Personal entries in the Codex $ picker. Prefer InstallRoot/skills alone for $ discovery.'
    SmokeTe01Code                  = 'TE01'
    SmokeTe02Code                  = 'TE02'
    SmokeTe03Code                  = 'TE03'
    SmokeTe04Code                  = 'TE04'
    SmokeExitSuccess               = 0
    SmokeExitFailure               = 1
    JsonConvertDepthShallow        = 5
    JsonConvertDepthDeep           = 8
}

$script:CodexSmokeMessage = @{
    Te01InvalidInstallRoot     = 'TE01: Codex agent ''codex'' smoke aborted - InstallRoot invalid or under USERPROFILE without -AllowUserHome. Detail: {0}'
    Te02PluginManifestMissing  = 'TE02: Codex agent ''codex'' smoke failed - plugin.json missing at: {0}'
    Te02PluginManifestInvalid  = 'TE02: Codex agent ''codex'' smoke failed - plugin.json is not valid JSON or missing required fields (name, version, description, skills, interface.displayName) at: {0}'
    Te02PluginSkillsMissing    = 'TE02: Codex agent ''codex'' smoke failed - plugin skills incomplete. Expected at least one skills/<kebab-id>/SKILL.md under: {0}'
    Te02HelpSkillsMissing      = 'TE02: Codex agent ''codex'' smoke failed - help-skills SKILL.md missing at: {0}'
    Te02SkillsCatalogMissing   = 'TE02: Codex agent ''codex'' smoke failed - skills catalog CATALOG.md missing at: {0}'
    Te03MarketplaceMissing     = 'TE03: Codex agent ''codex'' smoke failed - marketplace catalog missing at: {0}'
    Te03MarketplaceInvalid     = 'TE03: Codex agent ''codex'' smoke failed - marketplace.json invalid or has no plugins[] at: {0}'
    Te03MarketplaceEntryBroken = 'TE03: Codex agent ''codex'' smoke failed - marketplace entry ''{0}'' source.path broken (missing, not ./relative, or does not resolve). Expected path under InstallRoot; catalog: {1}; detail: {2}'
    Te04HooksMissing           = 'TE04: Codex agent ''codex'' smoke failed - hooks capable but hooks file missing at: {0} (filesystem only; trust /hooks UI is out of scope)'
    Te04HooksInvalid           = 'TE04: Codex agent ''codex'' smoke failed - hooks.json missing or not valid JSON at: {0}'
    RulesMissing               = 'Codex agent ''codex'' smoke failed - rules capable but InstallRoot/rules incomplete. Missing: {0}'
    AgentsMdMissing            = 'Codex agent ''codex'' smoke failed - AGENTS.md missing or empty at: {0}'
    AgentsPlaceholderResidual  = 'Codex agent ''codex'' smoke failed - AGENTS.md still contains unresolved {{…}} placeholders at: {0}'
    AgentsDocsLinkForbidden    = 'Codex agent ''codex'' smoke failed - AGENTS.md still references repo docs/ paths at: {0}'
    AgentsDualRootMissing      = 'Codex agent ''codex'' smoke failed - AGENTS.md missing dual-root callout or InstallRoot/plugin absolute paths at: {0}'
    HomeSkillsRootMissing      = 'Codex agent ''codex'' smoke failed - InstallRoot/skills (Codex $ discovery) missing at: {0}'
    HomeSkillsHelpSkillsMissing = 'Codex agent ''codex'' smoke failed - home skills ($ discovery) missing help-skills SKILL.md at: {0}'
    HomeSkillsCatalogMissing   = 'Codex agent ''codex'' smoke failed - home skills ($ discovery) missing skills catalog CATALOG.md at: {0}'
    UserSkillsRootMissing      = 'Codex agent ''codex'' smoke failed - USER skills root missing when mirror expected: {0}'
    UserSkillsIncomplete       = 'Codex agent ''codex'' smoke failed - USER skills path has skill folder without SKILL.md: {0}'
    UserSkillsHelpSkillsMissing = 'Codex agent ''codex'' smoke failed - USER-scope mirror missing help-skills SKILL.md at: {0}'
    UserSkillsCatalogMissing   = 'Codex agent ''codex'' smoke failed - USER-scope mirror missing skills catalog CATALOG.md at: {0}'
    SddLayoutMissing           = 'Codex agent ''codex'' smoke failed - SDD layout incomplete under InstallRoot. Missing: {0}'
    Passed                     = 'Codex Invoke-SmokeValidate PASS under {0} (filesystem-only; plugin + InstallRoot/skills ($ discovery) help-skills/CATALOG + marketplace + rules + materialized AGENTS.md + hooks files; absent/empty USER skills root OK without UserScope; trust /hooks UI out of scope - RN03).'
    FilesystemOnlyNote         = 'Smoke never invokes Codex runtime or /hooks trust UI.'
}

$script:CodexPublishMessage = @{
    CoreSkillsMissing       = 'Codex Publish-Skills: core skills source is missing: {0}'
    PublishedOk             = 'Codex Publish-Skills: published plugin + marketplace ({0} file(s) under plugin/skills) and home skills ($ discovery, {1} file(s) under {2})'
    PublishedOkWithUserScope = 'Codex Publish-Skills: published plugin + marketplace ({0} file(s) under plugin/skills), home skills ($ discovery, {1} file(s) under {2}), and USER-scope mirror ({3} file(s) under {4})'
    WhatIfOk                = 'Codex Publish-Skills: WhatIf - would publish plugin + marketplace + InstallRoot/skills ($ discovery) under {0}'
    WhatIfOkWithUserScope   = 'Codex Publish-Skills: WhatIf - would publish plugin + marketplace + InstallRoot/skills under {0} and USER-scope mirror under {1}'
    InstallRootRequired     = 'InstallRoot is required.'
    PlaceholderUnresolved   = 'Codex Publish-Skills: unresolved placeholder {0} remains under {1}'
    ManifestExtraFiles      = 'Codex Publish-Skills: .codex-plugin must contain only plugin.json; unexpected: {0}'
    MarketplaceSourceInvalid = 'Codex Publish-Skills: marketplace source.path must be ./prefixed relative path; got: {0}'
    MarketplacePluginMissing = 'Codex Publish-Skills: marketplace source.path does not resolve to an existing plugin root: {0}'
    CoreRouterMissing       = 'Codex Publish-Router: core router source is missing: {0}'
    RouterPublishedOk       = 'Codex Publish-Router: published materialized AGENTS.md from core/router to {0}'
    RouterWhatIfOk          = 'Codex Publish-Router: WhatIf - would publish materialized AGENTS.md under {0}'
    RouterSkillsHelpersMissing = 'Codex Publish-Router: Get-CodexNormalizedForwardSlashPath is missing; load Publish-CodexSkills.ps1 before Publish-Router.'
    RouterRepoDocsLinkForbidden = 'Codex Publish-Router: published AGENTS.md still references repo docs/ paths at: {0}'
    RouterDualRootIntro     = 'Codex InstallRoot `{0}` uses dual roots: home/plugin skills vs InstallRoot rules. Prefer absolute paths below. Invoke toolkit skills with `$<skill-id>` (for example `$help-skills`).'
    RouterDualRootNote      = 'Codex `$` discovery reads InstallRoot/skills (TOOLKIT_ROOT = InstallRoot). Plugin skills under InstallRoot/plugin remain for marketplace packaging (TOOLKIT_ROOT = plugin). Do not resolve skill `_shared` under InstallRoot/rules — rules and guardrails live under InstallRoot/rules only.'
    HooksPublishedOk        = 'Codex Publish-Hooks: published hooks/hooks.json under {0} (filesystem only; trust /hooks is manual)'
    HooksWhatIfOk           = 'Codex Publish-Hooks: WhatIf - would publish hooks under {0}'
    HooksSkippedNotCapable  = 'Codex Publish-Hooks: skipped - hooks capability is false; no hooks files written under {0}'
    CorePolicyMissing       = 'Codex Publish-Policy: core policy source is missing: {0}'
    PolicyPublishedOk       = 'Codex Publish-Policy: published {0} file(s) from core/policy to {1}'
    PolicyWhatIfOk          = 'Codex Publish-Policy: WhatIf - would publish core/policy to {0}'
    LiveUserScopeRequiresAllowUserHome = 'Codex Publish-Skills: live ~/.codex UserScope write to $HOME/.agents/skills requires -AllowUserHome.'
}

$script:CodexUninstallMessage = @{
    InstallRootRequired = 'InstallRoot is required.'
    RemovedOk           = 'Codex Uninstall-Toolkit: removed {0} keyed toolkit path(s) under {1} (RN07: no wholesale wipe of Codex config / alien files).'
    WhatIfOk            = 'Codex Uninstall-Toolkit: WhatIf - would remove {0} keyed toolkit path(s) under {1} (RN07: no wholesale wipe).'
    NothingFound        = 'Codex Uninstall-Toolkit: no known toolkit artifacts found under {0} (keyed scan; nothing removed).'
}
