#Requires -Version 5.1
<#
.SYNOPSIS
  Path, layout, and message constants for the Hermes adapter.

.DESCRIPTION
  Kept inside adapters/hermes so parallel US waves do not mutate scripts/_lib.
  Script-scoped hashtables are required by Publish-*/Smoke/Uninstall siblings.
#>

$script:HermesAdapterConstant = @{
    OfficialUserRootRelativePath     = '.hermes'
    OfficialUserRootDescription      = 'Official Hermes user root is under the user home as .hermes (equivalent to ~/.hermes). Live InstallRoot is that directory.'
    OfficialProjectRootRelativePath  = '.hermes'
    OfficialProjectRootDescription   = 'Official Hermes project scope uses a .hermes directory as InstallRoot (skills and AGENTS.md directly under it).'
    OfficialSkillsRelativePath       = 'skills'
    OfficialSkillsDescription        = 'Hermes skills publish under skills/<kebab-id>/SKILL.md relative to InstallRoot (live ~/.hermes/skills).'
    OfficialRulesRelativePath        = 'AGENTS.md'
    OfficialRulesDescription         = 'Hermes does not publish a rules/ tree. core/policy is folded into InstallRoot/AGENTS.md (same file as the router).'
    OfficialHooksRelativePath        = 'hooks'
    OfficialHooksDescription         = 'Hermes hooks capability is false. Publish-Hooks is a no-op: no Cursor hooks.json and no Hermes config.yaml hooks.'
    OfficialAgentsFileName           = 'AGENTS.md'
    OfficialAgentsDescription        = 'Hermes router and folded policy land in AGENTS.md at the InstallRoot scope (live ~/.hermes/AGENTS.md). Never SOUL.md.'
    FixtureRelativePath              = 'scripts/validation/fixtures/hermes'
    InstallRootOverrideParameter     = 'InstallRoot'
    InstallRootOverrideDescription   = 'Pass -InstallRoot to target an in-repo fixture or an explicit path (live: ~/.hermes). Paths under USERPROFILE require -AllowUserHome.'
    SkillsTrustNote                  = 'Project copies of skills need hermes skills trust (trusted_project_dirs in the user config). User-home ~/.hermes/skills does not. Missing CLI is skipped and does not fail publish.'
    ResolveInstallRootRelativePath   = 'scripts/_lib/Resolve-InstallRoot.ps1'
    CoreDirectoryName                = 'core'
    SkillsDirectoryName              = 'skills'
    PolicyDirectoryName              = 'policy'
    RouterDirectoryName              = 'router'
    RouterSourceFileName             = 'AGENTS.md'
    SddDirectoryName                 = 'sdd'
    GuardrailsFileName               = 'guardrails.md'
    SkillManifestFileName            = 'SKILL.md'
    CursorRuleExtension              = '.mdc'
    MarkdownExtension                = '.md'
    CursorRulesDirectoryName         = 'rules'
    PlaceholderToolkitRoot           = '{{TOOLKIT_ROOT}}'
    PlaceholderSddRoot               = '{{SDD_ROOT}}'
    PlaceholderGuardrailsPath        = '{{GUARDRAILS_PATH}}'
    TextFileExtensionPattern         = '\.(md|mdc|json|ps1|yml|yaml|txt)$'
    PathSeparatorForwardSlash        = '/'
    MemoryFileName                   = 'MEMORY.md'
    SoulFileName                     = 'SOUL.md'
    ConfigYamlFileName               = 'config.yaml'
    GitKeepFileName                  = '.gitkeep'
    SmokeExitCodeSuccess             = 0
    SmokeExitCodeFailure             = 1
    CompatClaudeRootRelativePath     = '.claude'
    CompatCursorRootRelativePath     = '.cursor'
    CompatSkillsDirectoryName        = 'skills'
    CompatRulesDirectoryName         = 'rules'
    HermesCliCommandName             = 'hermes'
    HermesSkillsTrustVerb            = 'skills'
    HermesSkillsTrustAction          = 'trust'
    PolicyFoldSectionHeading         = '## Toolkit always-on policy'
    PolicyFoldIntro                  = 'Hermes does not load a Cursor rules tree. Always-on policy from core/policy is folded into this file (idempotent overwrite of managed AGENTS.md).'
    PolicyFileHeadingPrefix          = '### '
    AssetsDirectoryName              = 'assets'
    SpawnBridgeAssetFileName         = 'spawn-bridge.md'
    SpawnBridgeSectionHeading        = '## Hermes spawn bridge (this host only)'
    DelegateTaskToolName             = 'delegate_task'
    MemorySeedContent                = "# Memory`n`nDurable notes for this Hermes instance. The toolkit creates this file only when it is missing and never overwrites it. Do not store secrets or gateway tokens here.`n"
    SkillsTrustStatusUserHome        = 'skipped-user-home'
    SkillsTrustStatusCliMissing      = 'skipped-cli-missing'
    SkillsTrustStatusAttempted       = 'attempted'
    SkillsTrustStatusError           = 'skipped-error'
    ForbiddenToolkitHooksJsonFileName = 'toolkit-session-start.json'
}

$script:HermesAdapterMessage = @{
    NotImplemented            = '{0} is not implemented yet for the Hermes adapter. Publish/smoke stubs must not mutate InstallRoot.'
    AgentIdRequired           = 'AgentId is required.'
    InstallRootRequired       = 'InstallRoot is required.'
    CapabilitiesReady         = 'Hermes adapter capabilities reported (skills + folded policy/router under InstallRoot modeling ~/.hermes). Publish-Hooks/Agents are no-ops. Uninstall-Toolkit removes keyed toolkit artifacts only (no wipe of InstallRoot / config.yaml / MEMORY.md / SOUL.md). MEMORY.md is seeded only when missing. Project skills trust is best-effort when the hermes CLI is present.'
    SddRootResolved           = 'Hermes SDD root resolved at {0}.'
    SddRootPrepared           = 'Prepared Hermes SDD root at {0} (sessions={1}; manifestCreated={2}).'
    SddRootWouldPrepare       = 'WhatIf: would prepare Hermes SDD root at {0} (sessions + seed manifest.json if missing).'
    ResolveInstallRootMissing = 'Resolve-InstallRoot helper not found at: {0}'
    CoreSkillsMissing         = 'Hermes Publish-Skills: core skills source is missing: {0}'
    PublishedOk               = 'Hermes Publish-Skills: published {0} file(s) from core/skills to {1}'
    WhatIfOk                  = 'Hermes Publish-Skills: WhatIf - would publish core/skills to {0}'
    CorePolicyMissing         = 'Hermes Publish-Policy: core policy source is missing: {0}'
    CoreRouterMissing         = 'Hermes Publish-Router: core router source is missing: {0}'
    PolicyPublishedOk         = 'Hermes Publish-Policy: folded {0} policy file(s) into {1}'
    PolicyWhatIfOk            = 'Hermes Publish-Policy: WhatIf - would fold core/policy into {0}'
    RouterPublishedOk         = 'Hermes Publish-Router: wrote AGENTS.md (router + folded policy) to {0}'
    RouterWhatIfOk            = 'Hermes Publish-Router: WhatIf - would write AGENTS.md to {0}'
    PlaceholderUnresolved     = 'Hermes publish: unresolved placeholder {0} remains under {1}'
    HooksNoOp                 = 'Hermes Publish-Hooks is a no-op (hooks=false). No Cursor hooks.json and no Hermes config.yaml hooks were written under {0}.'
    HooksWhatIfOk             = 'Hermes Publish-Hooks: WhatIf - no-op (hooks=false); would not write hooks under {0}'
    AgentsNoOp                = 'Hermes has no agents/*.md roster; Publish-Agents is a no-op. Host spawn is delegate_task (see SPAWN.md). Do not emit delegation YAML.'
    PluginNoOp                = 'Hermes has no marketplace plugin surface; plugin capability is false.'
    SmokePassed               = 'Hermes Invoke-SmokeValidate: PASS under {0} (native ~/.hermes-layout filesystem checks; policy folded into AGENTS.md; hooks not required).'
    SmokeTe02SkillsMissing    = 'Hermes Invoke-SmokeValidate TE02: expected native skills under {0} (at least one SKILL.md); path missing or empty after publish.'
    SmokeTe03PolicyFoldMissing = 'Hermes Invoke-SmokeValidate TE03: rules capability is true but folded policy heading missing in AGENTS.md at {0}.'
    SmokeTe03SpawnBridgeMissing = 'Hermes Invoke-SmokeValidate TE03: Hermes spawn bridge heading missing in AGENTS.md at {0}.'
    SmokeTe03RouterMissing    = 'Hermes Invoke-SmokeValidate TE03: router capability is true but AGENTS.md missing at {0}.'
    SmokeTe03ForbiddenRulesTree = 'Hermes Invoke-SmokeValidate TE03: toolkit must not publish a rules/ tree; found core/policy files under {0}.'
    SmokeTe03ForbiddenHooks   = 'Hermes Invoke-SmokeValidate TE03: hooks capability is false but toolkit hooks JSON was written at {0}.'
    SpawnBridgeAssetMissing   = 'Hermes Publish: spawn bridge asset missing: {0}'
    SmokeTe04CompatOnly       = 'Hermes Invoke-SmokeValidate TE04: Claude/Cursor compat paths present without native skills/AGENTS.md under InstallRoot {0}. Native write under InstallRoot (skills|AGENTS.md) is required.'
    SmokeTe05SddLayoutMissing = 'Hermes Invoke-SmokeValidate TE05: SDD layout incomplete under InstallRoot {0}. Missing: {1}'
    SmokeMemoryMissing        = 'Hermes Invoke-SmokeValidate: expected MEMORY.md seed at {0} when the file was missing before publish.'
    UninstallOk               = 'Hermes Uninstall-Toolkit: removed {0} toolkit artifact(s) under {1} (keyed only; config.yaml, MEMORY.md, SOUL.md, and alien files preserved).'
    UninstallWhatIfOk         = 'Hermes Uninstall-Toolkit: WhatIf - would remove {0} toolkit artifact(s) under {1} (keyed only; no wipe of InstallRoot / config.yaml).'
    UninstallNothingFound     = 'Hermes Uninstall-Toolkit: no known toolkit artifacts found under {0} (keyed scan; nothing removed).'
    ManagedTreeLibMissing     = 'Hermes Publish-Skills: managed tree lib missing after script-scope load: {0}'
    SkillsTrustUserHome       = 'Hermes Publish-Skills: skipped skills trust (InstallRoot is the official user .hermes home).'
    SkillsTrustCliMissing     = 'Hermes Publish-Skills: skipped skills trust (hermes CLI not found).'
    SkillsTrustAttempted      = 'Hermes Publish-Skills: attempted hermes skills trust for project InstallRoot {0} (non-fatal).'
    SkillsTrustError          = 'Hermes Publish-Skills: skills trust skipped after CLI error for {0} (non-fatal): {1}'
}
