#Requires -Version 5.1
<#
.SYNOPSIS
  Path and placeholder constants for the Antigravity adapter.

.DESCRIPTION
  Kept inside adapters/antigravity so parallel US waves do not mutate scripts/_lib.
#>

$script:AntigravityPathConstant = @{
    CoreDirectoryName                 = 'core'
    PolicyDirectoryName               = 'policy'
    RouterDirectoryName               = 'router'
    SkillsDirectoryName               = 'skills'
    PluginsDirectoryName              = 'plugins'
    ConfigDirectoryName               = 'config'
    SddDirectoryName                  = 'sdd'
    GuardrailsSourceFileName          = 'guardrails.md'
    GuardrailsOutputFileName          = 'GUARDRAILS.md'
    RouterSourceFileName              = 'AGENTS.md'
    SkillManifestFileName             = 'SKILL.md'
    DevPersonaSkillDirectoryName      = 'dev_persona'
    ManagedPluginDirectoryName        = 'agent-dev-toolkit'
    OfficialGuardrailsRelativePath    = 'config/plugins/agent-dev-toolkit/GUARDRAILS.md'
    OfficialDevPersonaRelativePath    = 'config/skills/dev_persona'
    OfficialDevPersonaSkillRelativePath = 'config/skills/dev_persona/SKILL.md'
    AlwaysApplyFrontmatterToken       = 'alwaysApply: true'
    PlaceholderToolkitRoot            = '{{TOOLKIT_ROOT}}'
    PlaceholderSddRoot                = '{{SDD_ROOT}}'
    PlaceholderGuardrailsPath         = '{{GUARDRAILS_PATH}}'
    TextFileExtensionPattern          = '\.(md|mdc|json|ps1|yml|yaml|txt)$'
    PathSeparatorForwardSlash         = '/'
    ForbiddenUnderscoreMandatePhrase  = 'use underscore folder names'
    SharedSkillsDirectoryName         = '_shared'
    KebabSkillFolderNamePattern       = '^[a-z0-9]+(-[a-z0-9]+)*$'
    UnderscoreSkillFolderNamePattern  = '^[a-z0-9]+(_[a-z0-9]+)+$'
    SmokeTe01Code                     = 'TE01'
    SmokeTe04Code                     = 'TE04'
    SmokeTe05Code                     = 'TE05'
    ManagedBlockBeginMarker           = '<!-- agent-dev-toolkit:managed:begin -->'
    ManagedBlockEndMarker             = '<!-- agent-dev-toolkit:managed:end -->'
    OfficialSkillsRelativePath        = 'config/skills'
    OfficialSkillsJsonRelativePath    = 'config/skills.json'
    OfficialAgentsMdRelativePath      = 'config/AGENTS.md'
    OfficialGeminiMdRelativePath      = 'config/GEMINI.md'
    OfficialGuardrailsMdDisplayPath   = 'config/plugins/agent-dev-toolkit/GUARDRAILS.md'
    OfficialDevPersonaSkillDisplayPath = 'config/skills/dev_persona/SKILL.md'
    GuardrailsGeneratedBanner         = @'
<!--
  Generated by agent-dev-toolkit Antigravity adapter Publish-Policy.
  Source of truth: core/policy (this toolkit).
-->
'@
    DevPersonaSkillFrontmatter        = @'
---
name: dev_persona
description: Developer persona and router guidance generated from core/router for Antigravity.
---

'@
    DevPersonaSkillIntro              = @'
# Developer persona

Generated from `core/router` (and policy pointers). Skill folders published by this toolkit stay **kebab-case**; do not treat underscore renames as mandatory product policy.

'@
    ManagedAgentsBlockBody            = @'
- Whenever you need to read restricted files under .gemini/config (such as skills.json), use the terminal tool run_command with Get-Content (Windows) or cat (Mac/Linux), because direct access via view_file is blocked by the system sandbox.
- On the first turn of a conversation, before answering about available skills or running a skill, read config/skills.json via Get-Content or cat, then resolve each entries[].path to discover installed skills.
- Toolkit skills live under config/skills/ as kebab-case folders registered in skills.json. Never require underscore folder renames; never search the current workspace for SKILL.md as a substitute for skills.json discovery.
- After resolving the skills path, read config/plugins/agent-dev-toolkit/GUARDRAILS.md and config/skills/dev_persona/SKILL.md before any mutating action.
- When the user says use skill [name] or /[name], open SKILL.md at config/skills/[name]/SKILL.md (kebab-case folder names) before acting.
'@
}

$script:AntigravityPublishMessage = @{
    InstallRootRequired     = 'InstallRoot is required.'
    CorePolicyMissing       = 'Antigravity Publish-Policy: core policy source is missing: {0}'
    CoreGuardrailsMissing   = 'Antigravity Publish-Policy: core guardrails source is missing: {0}'
    PolicyPublishedOk       = 'Antigravity Publish-Policy: wrote GUARDRAILS.md from core/policy to {0} ({1} source file(s))'
    PolicyWhatIfOk          = 'Antigravity Publish-Policy: WhatIf - would write GUARDRAILS.md to {0}'
    CoreRouterMissing       = 'Antigravity Publish-Router: core router source is missing: {0}'
    RouterPublishedOk       = 'Antigravity Publish-Router: wrote skill dev_persona from core/router to {0}; upserted managed blocks in AGENTS.md and GEMINI.md'
    RouterWhatIfOk          = 'Antigravity Publish-Router: WhatIf - would write skill dev_persona to {0} and upsert managed AGENTS.md/GEMINI.md blocks'
    ManagedBlockUpsertOk    = 'Antigravity Publish-Router: upserted managed block in {0}'
    PlaceholderUnresolved   = 'Antigravity publish: unresolved placeholder {0} remains under {1}'
    ForbiddenPhrasePresent  = 'Antigravity publish: forbidden underscore-mandate phrase remains under {0}'
}
