#Requires -Version 5.1
<#
.SYNOPSIS
  Path, layout, and message constants for the OpenHands adapter.

.DESCRIPTION
  Kept inside adapters/openhands so parallel US waves do not mutate scripts/_lib.
  Script-scoped hashtables are required by Publish-*/Smoke/Uninstall siblings.
#>

$script:OpenHandsAdapterConstant = @{
    OfficialUserRootRelativePath       = '.agents'
    OfficialUserRootDescription        = 'Official OpenHands user skills home is ~/.agents (live skills at ~/.agents/skills). Writing that path requires -AllowUserHome. Do not nest another .agents segment under it.'
    OfficialProjectRootRelativePath    = '.'
    OfficialProjectRootDescription     = 'Default InstallRoot is a project tree: AGENTS.md, .agents/skills, .agents/agents, .openhands, and .plugin at the repository root (not ~/.agents).'
    OfficialSkillsRelativePath         = '.agents/skills'
    OfficialSkillsDescription          = 'Project skills publish under .agents/skills/<kebab-id>/SKILL.md (Agent Skills; not legacy .openhands/microagents). Live user home ~/.agents uses skills/ directly under that InstallRoot.'
    OfficialUserSkillsRelativePath     = 'skills'
    OfficialRulesRelativePath          = 'AGENTS.md'
    OfficialRulesDescription           = 'OpenHands does not publish a Cursor rules/ .mdc tree. core/policy is folded into AGENTS.md together with the router.'
    OfficialHooksRelativePath          = '.openhands'
    OfficialHooksDescription           = 'Repository hooks publish as .openhands/hooks.json plus .openhands/hooks/*.sh (shell, not .ps1). Filesystem only; no Automation Server.'
    OfficialHooksScriptsRelativePath   = '.openhands/hooks'
    OfficialPluginRelativePath         = '.plugin'
    OfficialPluginManifestRelativePath = '.plugin/plugin.json'
    OfficialPluginDescription          = 'OpenHands-native plugin metadata is .plugin/plugin.json at the project root. Skills still load from .agents/skills without the plugin.'
    OfficialCustomAgentsRelativePath   = '.agents/agents'
    OfficialCustomAgentsDescription    = 'SDK/plugin agent roster markdown publishes under .agents/agents/*.md. Canvas Profile is a different surface and is not this roster.'
    OfficialAgentsFileName             = 'AGENTS.md'
    OfficialAgentsDescription          = 'OpenHands repository context is AGENTS.md at the project InstallRoot (loaded into the initial system prompt).'
    FixtureRelativePath                = 'scripts/validation/fixtures/openhands'
    InstallRootOverrideParameter       = 'InstallRoot'
    InstallRootOverrideDescription     = 'Pass -InstallRoot to target an in-repo project fixture or an explicit path. Live ~/.agents/skills requires -AllowUserHome. Paths under USERPROFILE require -AllowUserHome.'
    HooksFilesystemOnlyNote            = 'OpenHands hooks are filesystem-only shell scripts. Smoke never starts Canvas, Agent Server, or Automation Server.'
    ResolveInstallRootRelativePath     = 'scripts/_lib/Resolve-InstallRoot.ps1'
    CoreDirectoryName                  = 'core'
    SkillsDirectoryName                = 'skills'
    PolicyDirectoryName                = 'policy'
    RouterDirectoryName                = 'router'
    RouterSourceFileName               = 'AGENTS.md'
    AgentsDirectoryName                = 'agents'
    DotAgentsDirectoryName             = '.agents'
    SddDirectoryName                   = 'sdd'
    GuardrailsFileName                 = 'guardrails.md'
    SkillManifestFileName              = 'SKILL.md'
    SharedSkillsDirectoryName          = '_shared'
    CursorRuleExtension                = '.mdc'
    MarkdownExtension                  = '.md'
    ShellScriptExtension               = '.sh'
    PlaceholderToolkitRoot             = '{{TOOLKIT_ROOT}}'
    PlaceholderSddRoot                 = '{{SDD_ROOT}}'
    PlaceholderGuardrailsPath          = '{{GUARDRAILS_PATH}}'
    TextFileExtensionPattern           = '\.(md|mdc|json|ps1|yml|yaml|txt|sh)$'
    PathSeparatorForwardSlash          = '/'
    AssetsDirectoryName                = 'assets'
    AssetsHooksDirectoryName           = 'hooks'
    PluginDirectoryName                = '.plugin'
    PluginManifestFileName             = 'plugin.json'
    PluginName                         = 'agent-dev-toolkit'
    PluginVersion                      = '0.1.0'
    PluginDescription                  = 'Agent Dev Toolkit skills and repository hooks packaged as an OpenHands plugin. Project skills under .agents/skills work without installing this plugin.'
    PluginAuthor                       = 'agent-dev-toolkit'
    PluginSkillsManifestRelative       = './.agents/skills/'
    PluginHooksManifestRelative        = './.openhands/hooks.json'
    OpenHandsDirectoryName             = '.openhands'
    HooksDirectoryName                 = 'hooks'
    HooksJsonFileName                  = 'hooks.json'
    HooksSessionStartScriptName        = 'session_start.sh'
    HooksSessionStartCommandRelative   = '.openhands/hooks/session_start.sh'
    HooksSessionStartEventSnake        = 'session_start'
    HooksGuardPreToolScriptName        = 'guard_pre_tool.sh'
    HooksGuardPreToolPs1Name           = 'guard_pre_tool.ps1'
    HooksGuardPreToolCommandRelative   = '.openhands/hooks/guard_pre_tool.sh'
    HooksPreToolUseEventSnake          = 'pre_tool_use'
    HooksPreToolUseMatcher             = 'write|terminal|file_editor'
    HooksMatcherAll                    = '*'
    HooksTimeoutSeconds                = 5
    HooksTimeoutPreToolSeconds         = 10
    HooksDescription                   = 'agent-dev-toolkit OpenHands SessionStart + PreToolUse path/secrets guards (shell entry; filesystem publish only; no Automation Server).'
    SharedGuardCommonFileName          = 'GuardCommon.ps1'
    RulesDirectoryName                 = 'rules'
    RulesAlwaysOnHeading               = '## Rules (always-on)'
    RulesFoldedPointer                 = 'this AGENTS.md Rules (always-on) section'
    OrchestratorSessionMdcFileName     = 'orchestrator-session.mdc'
    OrchestratorSessionMdFileName      = 'orchestrator-session.md'
    GuardrailsMdcFileName              = 'guardrails.mdc'
    CompatClaudeRootRelativePath       = '.claude'
    CompatCursorRootRelativePath       = '.cursor'
    CompatSkillsDirectoryName          = 'skills'
    CompatRulesDirectoryName           = 'rules'
    SmokeExitCodeSuccess               = 0
    SmokeExitCodeFailure               = 1
    ConfigTomlFileName                 = 'config.toml'
    GitKeepFileName                    = '.gitkeep'
    JsonConvertDepthShallow            = 5
    JsonConvertDepthDeep               = 8
    SubagentsNone                      = 'none'
    KnownPolicyGuardrailsBaseName      = 'guardrails'
}

$script:OpenHandsAdapterConstant.RulesFoldIntro = @'
OpenHands does not publish a Cursor `rules/` tree. Toolkit `core/policy` is folded into this AGENTS.md (always-on repository context). Path-triggered skills under `.agents/skills` with `paths:` are a different mechanism — not this fold.

'@

$script:OpenHandsAdapterMessage = @{
    NotImplemented            = '{0} is not implemented yet for the OpenHands adapter. Stubs must not mutate InstallRoot.'
    AgentIdRequired           = 'AgentId is required.'
    InstallRootRequired       = 'InstallRoot is required.'
    CapabilitiesReady         = 'OpenHands adapter capabilities reported (skills under .agents/skills; policy folded into AGENTS.md; router AGENTS.md; shell hooks under .openhands; plugin .plugin/plugin.json; agents under .agents/agents; subagents=none). Uninstall-Toolkit removes keyed toolkit artifacts only. Live ~/.agents requires -AllowUserHome. SDD runtime prepared on sync.'
    SddRootResolved           = 'OpenHands SDD root resolved at {0}.'
    SddRootPrepared           = 'Prepared OpenHands SDD root at {0} (sessions={1}; manifestCreated={2}).'
    SddRootWouldPrepare       = 'WhatIf: would prepare OpenHands SDD root at {0} (sessions + seed manifest.json if missing).'
    ResolveInstallRootMissing = 'Resolve-InstallRoot helper not found at: {0}'
    ManagedTreeLibMissing     = 'OpenHands Publish-Skills: managed tree lib missing after script-scope load: {0}'
    CoreSkillsMissing         = 'OpenHands Publish-Skills: core skills source is missing: {0}'
    PublishedOk               = 'OpenHands Publish-Skills: published {0} file(s) from core/skills to {1} (plugin metadata at {2}; skills work without the plugin)'
    WhatIfOk                  = 'OpenHands Publish-Skills: WhatIf - would publish core/skills to {0} and .plugin/plugin.json'
    CorePolicyMissing         = 'OpenHands Publish-Policy: core policy source is missing: {0}'
    PolicyPublishedOk         = 'OpenHands Publish-Policy: folded {0} core/policy file(s) into {1} (no rules/ tree, no Cursor .mdc)'
    PolicyWhatIfOk            = 'OpenHands Publish-Policy: WhatIf - would fold core/policy into {0} (no rules/ tree)'
    CoreRouterMissing         = 'OpenHands Publish-Router: core router source is missing: {0}'
    RouterPublishedOk         = 'OpenHands Publish-Router: wrote AGENTS.md (router + folded policy) to {0}'
    RouterWhatIfOk            = 'OpenHands Publish-Router: WhatIf - would write AGENTS.md to {0}'
    CoreAgentsMissing         = 'OpenHands Publish-Agents: core agents source is missing: {0}'
    AgentsPublishedOk         = 'OpenHands Publish-Agents: published {0} agent file(s) from core/agents to {1} (SDK/plugin roster; Canvas Profile is not this tree)'
    AgentsWhatIfOk            = 'OpenHands Publish-Agents: WhatIf - would publish {0} agent file(s) to {1}'
    PlaceholderUnresolved     = 'OpenHands publish: unresolved placeholder {0} remains under {1}'
    HooksPublishedOk          = 'OpenHands Publish-Hooks: published {0} (session_start + guard_pre_tool; shell; filesystem only; no Automation Server)'
    HooksWhatIfOk             = 'OpenHands Publish-Hooks: WhatIf - would publish OpenHands hooks under {0}'
    HooksSkippedNotCapable    = 'OpenHands Publish-Hooks: skipped - hooks capability is false; no hooks files written under {0}'
    HooksAssetsMissing        = 'OpenHands Publish-Hooks: hook script asset is missing: {0}'
    PluginManifestMissing     = 'OpenHands Publish-Skills: failed to write plugin manifest at {0}'
    SmokePassed               = 'OpenHands Invoke-SmokeValidate: PASS under {0} (project layout filesystem checks only; no Canvas/Automation Server/sandbox). Adapter smoke: PASS'
    SmokeTe02SkillsMissing    = 'OpenHands Invoke-SmokeValidate TE02: expected Agent Skills under {0} (at least one SKILL.md); path missing or empty after publish. Do not use legacy microagents.'
    SmokeTe03PolicyNotFolded  = 'OpenHands Invoke-SmokeValidate TE03: rules capability is true but AGENTS.md is missing folded core/policy at {0} (OpenHands must not publish a Cursor rules/ tree).'
    SmokeTe03RulesTreePresent = 'OpenHands Invoke-SmokeValidate TE03: Cursor-style rules tree present at {0}; OpenHands folds policy into AGENTS.md and must not publish rules/*.mdc.'
    SmokeTe03HooksMissing     = 'OpenHands Invoke-SmokeValidate TE03: hooks capability is true but official hooks missing (expected {0} and {1}).'
    SmokeTe03RouterMissing    = 'OpenHands Invoke-SmokeValidate TE03: router capability is true but AGENTS.md missing at {0}.'
    SmokeTe03PluginMissing    = 'OpenHands Invoke-SmokeValidate TE03: plugin capability is true but .plugin/plugin.json missing or invalid at {0}.'
    SmokeTe03AgentsMissing    = 'OpenHands Invoke-SmokeValidate TE03: agents capability is true but roster markdown missing under {0}.'
    SmokeTe04CompatOnly       = 'OpenHands Invoke-SmokeValidate TE04: Claude/Cursor compat paths present without native OpenHands skills/hooks/AGENTS.md under InstallRoot {0}. Native project layout is required.'
    SmokeTe05SddLayoutMissing = 'OpenHands Invoke-SmokeValidate TE05: SDD layout incomplete under InstallRoot {0}. Missing: {1}'
    SmokeFilesystemOnlyNote   = 'Smoke validates files only; do not start OpenHands Canvas, Agent Server, or Automation Server.'
    UninstallOk               = 'OpenHands Uninstall-Toolkit: removed {0} toolkit artifact(s) under {1} (keyed only; alien files preserved).'
    UninstallWhatIfOk         = 'OpenHands Uninstall-Toolkit: WhatIf - would remove {0} toolkit artifact(s) under {1} (keyed only; no wipe of InstallRoot).'
    UninstallNothingFound     = 'OpenHands Uninstall-Toolkit: no known toolkit artifacts found under {0} (keyed scan; nothing removed).'
}
